### ISSUE TITLE
Add to MELPA

### ISSUE THREAD

**Issue by treymerkley** [veelenga/ameba.el#5]
Could you get this in there? It would make installation and configuration a bit easier.

**Comment by veelenga** [comment]
Will do. Thanks

**Comment by treymerkley** [comment]
Thank you! I'll really enjoy getting started in what'll probably be my favorite language using my favorite text editor.

**Comment by veelenga** [comment]
I have opened PR to melpa: https://github.com/melpa/melpa/pull/6138

**Comment by veelenga** [comment]
https://melpa.org/#/?q=ameba
