### ISSUE TITLE
Create a temp file folder1/flycheck_app.cr when edit folder1/app.cr, which broken compiler process.

### ISSUE THREAD

**Issue by zw963** [veelenga/ameba.el#8]
Please check here, thank you.

https://github.com/flycheck/flycheck/issues/1949

**Comment by veelenga** [comment]
Ok, i will take a look. Thanks

**Comment by veelenga** [comment]
Related: https://github.com/flycheck/flycheck/issues/334

**Comment by veelenga** [comment]
As far as I understand, this behavior in flycheck is mandatory and you can't opt out. Is the autogenerated file cleaned after it is being created?
